cloud:
  files:
    path:
      /Users/seungyoungoh/Library/Mobile Documents/com~apple~CloudDocs/home/workspace/log/public
server:
  ssl:
    enabled: true
    key-store: classpath:ssl/keystore.p12
    key-store-password: logger#01
    key-store-type: PKCS12
