cloud:
  files:
    path: "/Users/seungyoungoh/Library/Mobile Documents/iCloud~md~obsidian/Documents/seung-00/4. work/blog/log/public"
management:
  endpoints:
    web:
      exposure:
        include: "*"
